version: "3.7"

services:
  seeksense_webui:
    build:
      context: .
    ports:
      - "127.0.0.1:8181:8181"
    networks:
      - seeksense_database
      - seeksense_webui
      - seeksense_embeddings
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: seeksense_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: seeksense_db
      MYSQL_USER: ss_user
      MYSQL_PASSWORD: abcd123
    networks:
      - seeksense_database
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: unless-stopped

networks:
  seeksense_database:
    driver: bridge
  seeksense_webui:
    name: seeksense_webui
    driver: bridge
  seeksense_embeddings:
    name: seeksense_embeddings
    external: true

volumes:
  mariadb_volume:
